package com.trustee.backend.auth.dto;

public class AuthInitRequest {
    private String clientData;
    private String name;
    private String carrier;
    // [New] The UUID generated by the Entruster to correlate the session
    private java.util.UUID authRequestId;

    public String getClientData() {
        return clientData;
    }

    public void setClientData(String clientData) {
        this.clientData = clientData;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCarrier() {
        return carrier;
    }

    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }

    public java.util.UUID getAuthRequestId() {
        return authRequestId;
    }

    public void setAuthRequestId(java.util.UUID authRequestId) {
        this.authRequestId = authRequestId;
    }
}
